/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.12.1/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.3.21"

    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}

buildscript { dependencies { classpath(kotlin("gradle-plugin", version = "2.3.21")) } }

dependencies {
    implementation("com.google.devtools.ksp:symbol-processing-api:2.3.11")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    implementation(libs.modtyinfo)
}



// Publish the plugin JAR (which includes annotations)
publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "lynxpo.ktts"
            artifactId = "ktts-plugin"  // ARTIFACT_ID
            version = "1.0.3"
            from(components["java"])
        }
    }
    repositories {
        mavenLocal()  // Publish to ~/.m2/repository
    }
}

kotlin {
    jvmToolchain(21)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by
                getting(JvmTestSuite::class) {
                    // Use Kotlin Test test framework
                    useKotlinTest("2.0.21")
                }

        // Create a new test suite
        val functionalTest by
                registering(JvmTestSuite::class) {
                    // Use Kotlin Test test framework
                    useKotlinTest("2.0.21")

                    dependencies {
                        // functionalTest test suite depends on the production code in tests
                        implementation(project())
                    }

                    targets {
                        all {
                            // This test suite should run after the built-in test suite has run its
                            // tests
                            testTask.configure { shouldRunAfter(test) }
                        }
                    }
                }
    }
}

gradlePlugin {
    // Define the plugin
    val greeting by
            plugins.creating {
                id = "ktts-plugin"
                implementationClass = "lynxpo.ktts.processor.KttsPlugin"
            }
}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}
