packages:
  - "packages/*"
  - "packages/tools/*"
  - "packages/modules/*"
  - "packages/plugins/ktts"
  - "packages/plugins/style-dict-rsbuild-plugin"

allowBuilds:
  esbuild: true

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - esbuild
