// Copyright 2026 The Lynxpo Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#import "HostViewController.h"
#import <Lynx/LynxConfig.h>
#import <Lynx/LynxEnv.h>
#import <Lynx/LynxView.h>
#import <Lynx/LynxTemplateData.h>
#import "LynxGeneratedLibraryRegistry.h"

@interface HostViewController () <LynxViewLifecycle>
@property(nonatomic, strong) LynxView *lynxView;
@end

@implementation HostViewController

- (void)viewDidLoad {
  [super viewDidLoad];
  self.view.backgroundColor = [UIColor whiteColor];

  // Build a LynxConfig reusing the shared LynxEnv template provider, then let
  // Autolink auto-register every @lynxpo/mods-* native module
  // (LynxGeneratedLibraryRegistry is generated by use_lynx_library!).
  LynxConfig *config =
      [[LynxConfig alloc] initWithProvider:[LynxEnv sharedInstance].config.templateProvider];
  [[LynxGeneratedLibraryRegistry new] setup:config];

  LynxView *lynxView = [[LynxView alloc] initWithBuilderBlock:^(LynxViewBuilder *builder) {
    builder.config = config;
    builder.screenSize = self.view.bounds.size;
    builder.fontScale = 1.0;
    builder.enableGenericResourceFetcher = YES;
    // Match the Explorer: render everything on the UI thread so the prop bridge
    // and UI component setters run on main (the engine default runs them on a
    // background thread, which aborts in NSInvocation/_getFrameDescriptor).
    [builder setThreadStrategyForRender:LynxThreadStrategyForRenderAllOnUI];
  }];
  lynxView.frame = self.view.bounds;
  lynxView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  lynxView.preferredLayoutWidth = self.view.bounds.size.width;
  lynxView.preferredLayoutHeight = self.view.bounds.size.height;
  lynxView.layoutWidthMode = LynxViewSizeModeExact;
  lynxView.layoutHeightMode = LynxViewSizeModeExact;
  lynxView.enableAutoLayout = YES;
  [self.view addSubview:lynxView];
  self.lynxView = lynxView;
  [lynxView addLifecycleClient:self];

  // Load the bundled showcase template. The URL is a bare resource name that
  // HostTemplateProvider resolves against the app bundle. loadTemplateFromURL:
  // takes an NSString*, NOT an NSURL* (passing an NSURL crashes with an
  // unrecognized selector inside -[LynxTemplateRender processUrl:]).
  LynxTemplateData *initData = [[LynxTemplateData alloc] initWithDictionary:@{}];
  [lynxView loadTemplateFromURL:@"host.lynx.bundle" initData:initData];
  [lynxView triggerLayout];
}

@end
