import Foundation
import SwiftSyntax

/// A SwiftSyntax visitor that collects static typeInfo properties generated by @Typed macro
class TypeInfoVisitor: SyntaxVisitor {
    /// Dictionary mapping class names to their typeInfo string values
    var typeInfos: [String: String] = [:]
    override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
        // Check if this is a static property
        if node.modifiers.contains(where: { $0.name.text == "static" }) {
            // Look for properties named "typeInfo"
            for binding in node.bindings {
                if let pattern = binding.pattern.as(IdentifierPatternSyntax.self),
                    pattern.identifier.text == "typeInfo",
                    // Check if it has an initializer
                    let initializer = binding.initializer?.value
                {

                    // Extract the class/struct name from the parent declaration
                    if let classDecl = node.parent?.parent?.as(ClassDeclSyntax.self) {
                        let className = classDecl.name.text
                        // Extract the string literal value
                        if let stringLiteral = initializer.as(StringLiteralExprSyntax.self),
                            let firstSegment = stringLiteral.segments.first?.as(
                                StringSegmentSyntax.self)
                        {
                            typeInfos[className] = firstSegment.content.text
                        }
                    } else if let structDecl = node.parent?.parent?.as(StructDeclSyntax.self) {
                        let structName = structDecl.name.text
                        // Extract the string literal value
                        if let stringLiteral = initializer.as(StringLiteralExprSyntax.self),
                            let firstSegment = stringLiteral.segments.first?.as(
                                StringSegmentSyntax.self)
                        {
                            typeInfos[structName] = firstSegment.content.text
                        }
                    }
                }
            }
        }

        return .visitChildren
    }
}
