import ArgumentParser
import Foundation
import Logging
import NMBSwiftInspect
import SwiftDiagnostics
import SwiftParser
import SwiftSyntax

enum CollectorErr: Error {
    case failed(msg: String)
}
@main
struct NMBSwiftInspectCollector: ParsableCommand {
    @Option(
        name: .customLong("output-directory"), help: "Directory where JSON files will be written")
    var outputDirectory: String

    @Option(
        name: .customLong("source-files"), parsing: .upToNextOption,
        help: "Swift source files to process")
    var sourceFiles: [String]

    func run() throws {
        // Ensure output directory exists
        let fm = FileManager.default
        try fm.createDirectory(
            atPath: outputDirectory, withIntermediateDirectories: true, attributes: nil)
        print("outputDirectory --> \(outputDirectory)")
        // Look for static typeInfo properties that were generated by @Typed macro
        let visitor = TypeInfoVisitor(viewMode: .sourceAccurate)
        // Process each source file
        for sourceFile in sourceFiles {
            do {
                // Read the source file
                let sourceData = try Data(contentsOf: URL(fileURLWithPath: sourceFile))
                guard let sourceCode = String(data: sourceData, encoding: .utf8) else {
                    continue
                }

                // Parse the source code using SwiftParser instead of SwiftSyntaxParser
                let sourceFile = Parser.parse(source: sourceCode)

                visitor.walk(sourceFile)

                // Save collected type info to output directory
                for (className, typeInfoString) in visitor.typeInfos {
                    // Try to extract and parse ClassInfo from the typeInfo string
                    if let classInfo = ClassInfoExtractor.extractClassInfo(from: typeInfoString) {
                        // Create a formatted JSON file with pretty printing
                        let outputPath = URL(fileURLWithPath: outputDirectory)
                            .appendingPathComponent("\(className).json")
                        try ClassInfoExtractor.writeClassInfoToFile(classInfo, to: outputPath)
                        print("Wrote formatted type info for \(className) to \(outputPath.path)")
                    } else {
                        // Fallback to raw string if parsing fails
                        let outputPath = URL(fileURLWithPath: outputDirectory)
                            .appendingPathComponent("\(className).raw.json")
                        try typeInfoString.write(to: outputPath, atomically: true, encoding: .utf8)
                        print("Wrote raw type info for \(className) to \(outputPath.path)")
                    }
                }
            } catch {
                print("Error processing \(sourceFile): \(error)")
            }
        }

        // Create an index file listing all the collected types
        let indexPath = URL(fileURLWithPath: outputDirectory).appendingPathComponent("index.json")
        let indexContent = try JSONEncoder().encode(visitor.typeInfos.keys.sorted())
        try indexContent.write(to: indexPath)
        print("Wrote type index to \(indexPath.path)")
    }
}
